### ISSUE TITLE
Automate Bungie API Bindings

### ISSUE THREAD

**Issue by SK83RJOSH** [direwolves-of-the-frost/woofbot#2]
The [Bungie API](https://github.com/Bungie-net/api) is [entirely documented](https://github.com/Bungie-net/api/blob/master/openapi.json) as an [OpenAPI](https://swagger.io/specification/) compatible file. We should be able to generate the majority of the TypeScript bindings automatically using the documentation.

Let's publish the `bungie-api` folder as it's own module once it's relatively complete.

Goals:
- [x] Automatically generate types
- [ ] Automatically generate modules

**Comment by WinterWolfdog** [comment]
Sounds good to me

**Comment by SK83RJOSH** [comment]
Moved to [bungie-net #1](https://github.com/direwolves-of-the-frost/bungie-net/issues/1).
